const mongoose = require("mongoose");
const Schema = mongoose.Schema;

const advertSchema = new Schema({
    name: String,
    username: String,
    credit: Number,
    created_at: {type: Date, default: Date.now },
    updated_at: Date,
    ads: [{
      _id: String,
      ad_type: String,
      ad_width: Number,
      ad_height: {type: Number},
      ad_credits: {type: Number},
      ad_timer: {type: Number},
      ad_link: {type: String},
      ad_target: {type: String},
      ad_status: {type: String},
      ad_active: {type: String},
      ad_impressions: [{
        ad_browser: {type: String},
        ad_platform: {type: String},
        ad_url: {type: String},
        geoplugin_areaCode: {type: String},
        geoplugin_city: {type: String},
        geoplugin_continentCode: {type: String},
        geoplugin_continentName:{type: String},
        geoplugin_countryCode: {type: String},
        geoplugin_countryName: {type: String},
        geoplugin_currencyCode: {type: String},
        geoplugin_currencyConverter:{type: String},
        geoplugin_currencySymbol: {type: String},
        geoplugin_currencySymbol_UTF8: {type: String},
        geoplugin_delay: {type: String},
        geoplugin_dmaCode:{type: String},
        geoplugin_euVATrate: {type: String},
        geoplugin_inEU: {type: String},
        geoplugin_latitude: {type: String},
        geoplugin_locationAccuracyRadius: {type: String},
        geoplugin_longitude: {type: String},
        geoplugin_region: {type: String},
        geoplugin_regionCode: {type: String},
        geoplugin_regionName: {type: String},
        geoplugin_request: {type: String},
        geoplugin_status: {type: String},
        geoplugin_timezone:{type: String},
        created_at: {type: Date, default: Date.now }
      }],
      ad_clicks: [{
        ad_browser: {type: String},
        ad_platform: {type: String},
        ad_url: {type: String},
        geoplugin_areaCode: {type: String},
        geoplugin_city: {type: String},
        geoplugin_continentCode: {type: String},
        geoplugin_continentName:{type: String},
        geoplugin_countryCode: {type: String},
        geoplugin_countryName: {type: String},
        geoplugin_currencyCode: {type: String},
        geoplugin_currencyConverter:{type: String},
        geoplugin_currencySymbol: {type: String},
        geoplugin_currencySymbol_UTF8: {type: String},
        geoplugin_delay: {type: String},
        geoplugin_dmaCode:{type: String},
        geoplugin_euVATrate: {type: String},
        geoplugin_inEU: {type: String},
        geoplugin_latitude: {type: String},
        geoplugin_locationAccuracyRadius: {type: String},
        geoplugin_longitude: {type: String},
        geoplugin_region: {type: String},
        geoplugin_regionCode: {type: String},
        geoplugin_regionName: {type: String},
        geoplugin_request: {type: String},
        geoplugin_status: {type: String},
        geoplugin_timezone:{type: String},
        created_at: {type: Date, default: Date.now }
      }],
      created_at: Date,
      updated_at: Date

    }]
});

module.exports = mongoose.model("Advert", advertSchema)